### ISSUE TITLE
[Question] Why does it require a manual reload?

### ISSUE THREAD

**Issue by mklaber** [Maxam0001/TikTokLiveStreamURLHelper#4]
Hiya, what's the limitation that requires you manually reload the page when navigating to a new stream?

> It is important to note that navigating to a new stream by clicking on other video thumbnails does NOT refresh the stream URL.

Is it a limitation of TikTok (e.g., necessary information is only retrievable on first page load and can't find it after page navigation) or of the user script? (e.g., can't detect the page changed and therefore can't rebuild the button or something)

Depending on the root issue, I might be able to help but thought I'd ask first.

**Comment by Maxam0001** [comment]
The original version of this script pulled the URL directly from an object built by the TikTok scripts. The URL cached in that object was valid on navigating directly to the page, but wasn't getting updated if you click on another video. 

The past two versions of the script get the URL by directly querying the TikTok servers. It's entirely possible that the limitation is not in play anymore because of this, but I didn't really test, as I'm not really into TikTok (surprise!). I just wrote this because I needed to capture one specific stream a couple of months ago.

**Comment by Maxam0001** [comment]
No response, so closing this.

**Comment by mklaber** [comment]
Oops, sorry, thought I replied. 

You can safely remove that warning from the README.

**Comment by Maxam0001** [comment]
Oh ok, thanks for checking!
